# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require_relative 'apimatic_calculator/api_helper.rb'
require_relative 'apimatic_calculator/configuration.rb'
require_relative 'apimatic_calculator/apimatic_calculator_client.rb'

# Http
require_relative 'apimatic_calculator/http/http_call_back.rb'
require_relative 'apimatic_calculator/http/http_client.rb'
require_relative 'apimatic_calculator/http/http_method_enum.rb'
require_relative 'apimatic_calculator/http/http_request.rb'
require_relative 'apimatic_calculator/http/http_response.rb'
require_relative 'apimatic_calculator/http/http_context.rb'
require_relative 'apimatic_calculator/http/unirest_client.rb'

# Models
require_relative 'apimatic_calculator/models/base_model.rb'
require_relative 'apimatic_calculator/models/person.rb'
require_relative 'apimatic_calculator/models/operation_type_enum.rb'

# Exceptions
require_relative 'apimatic_calculator/exceptions/api_exception.rb'

# Controllers
require_relative 'apimatic_calculator/controllers/base_controller.rb'
require_relative 'apimatic_calculator/controllers/simple_calculator_controller.rb'
