# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApimaticCalculator
  class Person < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :person

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["person"] = "Person"
      end
      @hash
    end

    def initialize(person = nil)
      @person = person
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        person = hash["Person"]

        # Create object from extracted values
        Person.new(person)
      end
    end
  end
end
